### ISSUE TITLE
Failure on on demos (2014 era)

### ISSUE THREAD

**Issue by Hona** [demostf/parser#20]
Here's an example STV demo that fails:

[auto-20140701-233440-jump_propel_fixed_v3.zip](https://github.com/demostf/parser/files/14985458/auto-20140701-233440-jump_propel_fixed_v3.zip)

I was able to extract chat messages, by just ignoring the failure in the code, but a proper fix would be better.

Here's the commit that allowed me to continue: https://github.com/Hona/parser/commit/852d0aac31dc02a36e82d2421020e79092497f75

**Comment by icewind1991** [comment]
Fixed with ab87b34

**Comment by Hona** [comment]
I pulled main & tested with the demo I provided with no issues, thanks :)
